servers = 'nats://127.0.0.1:4222'

# For emnist
dataset = 'emnist'
image_size = 32
channel_size = 1
n_class = 47

# For cinic10
# dataset = 'cinic1'
# image_size = 32
# channel_size = 3
# n_class = 10

# Evaluation setting
gan_augmentation = True
static_augmentation = False
only_static_augmentation = False
shared_augmentation = False
replace_fake_with_real = False

# Hyperparameter of federated learning and GANDALF
n_clients = 20
n_mediators = 2
n_gans = 1
n_gpus = 2
local_epochs = 3
group_epochs = 1
global_epochs = 60
batch_size = 128

# Hyperparameter of GAN models, but they are not important here
z_size = 128
g_lr = .0001
d_lr = .0001
output_dir = './image'
g_penalty = 10.0
n_critic = 5
n_samples = 64

# Hyperparameter of GAN data augmentation
aug_factor = 0.07

# Differential privacy setting for local data distributions
dist_epsilon = 0.9
dist_delta = 0.9
dist_sensitivity = 0.001

# Differential privacy setting for model weights
weight_epsilon = 0.33
weight_delta = 1
weight_sensitivity = 0.00001

# Path of local datasets and different kinds of augmented datasets
datainfo_path = '../the path of local datasets/datainfo.data'
gan_weight_path = '../the path of trained GAN model weights'
labeling_weight_path = '../the path of pretrained classification model'

whole_dataset_path = '../the path of the raw dataset, you can find it in the data generation'
original_dataset_path = '../the path of local datasets generated by data generation'
shared_dataset_path = '/../the path of globally shared dataset'

gan_aug_dataset_path = '/../the path of local datasets augmented by GAN models'
shared_aug_dataset_path = '/../the path of local datasets augmented by globally shared dataset'
static_aug_dataset_path = '/../the path of local datasets augmented by static data augmentation'

