# node: 2
servers = 'nats://127.0.0.1:4222'

# For emnist
dataset = 'emnist'
image_size = 32
channel_size = 1
num_class = 47

# For cinic10
# dataset = 'cinic1'
# image_size = 32
# channel_size = 3
# num_class = 10

n_clients = 20
n_clients_per_round = 4
n_gpus = 2

batch_size = 128
local_epochs = 3
global_epochs = 150

dist_epsilon = 0.9
dist_delta = 0.9
dist_sensitivity = 0.001
weight_epsilon = 0.5
weight_delta = 0.1
weigyht_sensitivity = 0.001

datainfo_path = '../the path of local datasets/datainfo.data'
original_dataset_path = '../the path of local datasets generated by data generation'